### PR TITLE
adds dark and light svg logo to header

### PR DESCRIPTION
**Pull request by jakebogan01**
I went ahead and added a light and dark logo to the header. I commented out the old  SVG logo as well as the light SVG logo, leaving the dark logo up to view. I also switched where the link tag is, so it only wraps around the logo and doesn't span across the header.

### CODE REVIEW

**Comment by xuelink** [comment]
Screenshot 2024-04-11 at 1 20 36 AM
Screenshot 2024-04-11 at 1 20 47 AM
@jakebogan01 dark and light mode looks like that

**Comment by xuelink** [comment]
@jakebogan01 for both of them, it can stay the same because we are not changing the color of headers for both themes, i think it is also better to use it without background something like https://github.com/langxapp/branding/blob/main/app-resources/icon-foreground.png

**Comment by xuelink** [comment]
@jakebogan01 for example in our social media posts, its used like that for the yellow background and header of the website also doesnt change for the dark/light theme. We can use it the same here as well ;)
Screenshot 2024-04-11 at 1 34 30 AM

**Comment by jakebogan01** [comment]
@xuelink I understand, I will remove the dark logo and keep the other one. I'll have the logo look just like that 👍

**Comment by jakebogan01** [comment]
@xuelink I removed the dark and old SVG logo and replaced it with a normal logo as referenced in your image above. Ready for your review

**Review by xuelink — COMMENTED** [review]
Looks better! But still it changes by theme


https://github.com/langxapp/website/assets/3280475/b2bd78d3-b682-44d3-92fd-a342e2ce233a

**Comment by xuelink** [comment]
@jakebogan01 If you are agree with that, i can attach new commit here to fix it and merge it ;) Best

**Comment by jakebogan01** [comment]
@xuelink I tried to replicate that issue, the logo doesn't change based on the theme for me. What browser are you using?

**Comment by xuelink** [comment]
@jakebogan01 adding `fill="#000"` related parts of svg fixed.

My Browser:
Screenshot 2024-04-12 at 5 54 14 PM

**Comment by xuelink** [comment]
@jakebogan01 We are also talking about this repo on DG, #codebase channel, Feel free to join: [invitation](https://discord.com/invite/2D3jW2YDgS)

**Comment by jakebogan01** [comment]
@xuelink thanks for fixing that. Should have thought about that myself. Thanks again, I'll take a look at that today

**Pull request merged**
