### PR TITLE
updates footer design and adds additional links

### PR DESCRIPTION
**Pull request by jakebogan01**
@xuelink I updated the footer design, as well as added the 3 new links. I tested it on 4 major browsers. Safari, Firefox, Chrome and Edge so far. If you see anything out of the ordinary let me know.

image

### CODE REVIEW

**Review by xuelink — CHANGES_REQUESTED** [review]
it is actually better than i thought! but if you want to add another section like 

**Open Source**: under all github related links,
**Company** : all our subdomains and add `Branding` (https://github.com/langxapp/branding)
**Legal** : ok

- can you please update https://backlog.langx.io under **Company** section

**Comment by xuelink** [comment]
We also add new section for Token seperately instead of listing under `Company`, because day by day we will increase these links about token.

**Token**
- Website: https://token.langx.io/
- Twitter: [@langx_token](https://twitter.com/langx_token)
- Whitepaper: [Gitbook Draft](https://app.gitbook.com/invite/0n6eGkPoppmsyoZuw2GO/I9eV3C08ufDq2xWLjeVn)

**Comment by jakebogan01** [comment]
@xuelink Yeah I can try and add more links and see how it goes!

**Comment by jakebogan01** [comment]
@xuelink I added more columns and links, let me know what you think. Not sure what you meant by the comparisons though

**Review by xuelink — APPROVED** [review]

**Review by xuelink — APPROVED** [review]
Couldnt be better than it is! Thank you, im gonna fix some capital letter typo and merge it!

**Comment by jakebogan01** [comment]
@xuelink No problem!

**Pull request merged**
